#Zuul routes. "/user-service" 이 경로로 유입되는 것은 http://localhost:8083 서버로 연결한다.
zuul:
  routes:
    user-service.path: /user-service/**
    user-service.url: http://localhost:8083
  # 예외 무시 처리
  ignored-services: '*'
  ignored-patterns: /**/admin/**
  #타임아웃 설정
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000

# Ribbon 사용안함.
ribbon:
  eureka:
    enabled: false

# 서버 포트 설정
server:
  port: 8080